### ISSUE TITLE
Reboot failure using qemu

### ISSUE THREAD

**Issue by riceblast** [NeilKleistGao/dandelinux#1]
**OS and emulator version**
ubuntu 20.04
qemu 4.2.1

**Arch Linux installation reference**
https://zhuanlan.zhihu.com/p/109261196?utm_id=0

**Packages installed using paceman**
```
# All installation are according to reference tutorial
pacman -Sy net-tools
pacman -S tree
pacstrap /mnt base base-devel 
# Packages blow are installed after arch-chroot
pacman -S grub
pacman -S os-prober
pacman -S vim
pacman -S net-tools
```

**Qemu scripts used for installation** 
1. vm.sh (used to install dandelinux)
```
# before ./vm.sh, run: qemu-img create -f qcow2 dande.cow 40G
# vm.sh
qemu-system-x86_64 -cpu host -smp 4,sockets=1,cores=4,threads=1 \
                   -m 4G -enable-kvm \
                   -cdrom ./dandelinux-0.0.1-x86_64.iso \
                   -hda ./dande.cow \
                   -boot order=d
```
2. run.sh (used to boot dandelinux after installation)
```
qemu-system-x86_64 -cpu host -smp 4,sockets=1,cores=4,threads=1 \
                   -m 4G -enable-kvm \
                   -hda ./dande.cow \
```

**Bug**
1. After dandelinux was installed, it can't reboot successfully
  - **bug description**
When execute`grub-mkconfig -o /boot/grub/grub.cfg`, grub can't find vmlinuz and initramfs
![image](https://user-images.githubusercontent.com/44642638/236603540-7f750103-206f-4ff1-9872-7c6ee71ff756.png)
  If I shutdown dandelinux and run ./run.sh，qemu will enter grub command line，and I need to manually choose vmlinuz and initramfs, thus can't reboot successfully
![image](https://user-images.githubusercontent.com/44642638/236603609-1c6e5d00-9363-4444-8cf6-99c4ae5db0ac.png)

  - **Try to fix (didn't work)**
  I find vmlinuz and initramfs in directory: `run/archiso/bootmnt/arch/boot/x86_64/`, and copy files to `/mnt/boot`
![image](https://user-images.githubusercontent.com/44642638/236603868-845c6034-af9d-44bf-9bb3-f1f08ac872c5.png)
  After I run `arch-chroot /mnt` and re-run `grub-mkconfig`，now grub-mkconfig can find vmlinuz and initramfs，
![image](https://user-images.githubusercontent.com/44642638/236604229-2997c8ea-359b-4a96-9fcb-5e7e930a2a0a.png)
  after shutdown and reboot using run.sh, I can see grub, 
![image](https://user-images.githubusercontent.com/44642638/236605867-bf6cfc7a-a2ec-49e2-ad99-fdece59fb7ad.png)
  then I choose 'arch linux' and boot, 
![image](https://user-images.githubusercontent.com/44642638/236605950-666747fe-904e-42ec-821b-ac6f307227ac.png)  
  then, grub will stuck at "Load Linux linux..., Loading initial ramdisk..."，and then report error
![image](https://user-images.githubusercontent.com/44642638/236605927-aff9145d-f56b-4e3f-a57e-c69d741859f1.png)

**Comment by NeilKleistGao** [comment]
Please refer to `dandelinux/airootfs/root/min_test.sh`. Re-open this issue if the same problem appears.
